# Site settings
title: 'Yanhh blog'
email: yanhh0@163.com
url: 'http://yanhh0.github.io' # the base hostname & protocol for your site
github_repo: 'https://github.com/yanhh0/yanhh0.github.io/'

collections_dir: blog
collections:
  knowledges:
    output: true
  majors:
    output: true
  reprints:
    output: true
  reprints_cs:
    output: true
  reprints_cs_minor:
    output: true
  reprints_news:
    output: true
  tabs:
    output: true
  tweets:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

# SNS settings
baidu_username: 51杭
weibo_username: 午后曳航hh
zhihu_username: 杭01
github_username: yanhh0
wikipedia_username: Yanhh
# twitter_username:

# Build settings
markdown: kramdown
