# Site settings
title: The blog of Yanhh
SEOTitle: The blog of Yanhh
email: yanhh0@163.com
description: >
  Chinese Student, Grade Eleven

  Computer Science, Mathematics, Arts, and More
url: "http://yanhh0.github.io" # the base hostname & protocol for your site

collections_dir: blog
collections:
  edits:
    output: true
  updatings:
    output: true
  tabs:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
  -
    scope:
      path: "tabs"
    values:
      layout: "reprint"

# SNS settings
weibo_username: 午后曳航hh
zhihu_username: 杭01
github_username: yanhh0
# twitter_username:

# Build settings
markdown: kramdown
