# Site settings
title: 午后曳航的博客
email: yanhh0@163.com
description: >
  Chinese Student, Grade Eleven

  Computer Science, Mathematics, Arts, and More
url: "http://yanhh0.github.io" # the base hostname & protocol for your site
github_repo: 'https://github.com/yanhh0/yanhh0.github.io/'

collections_dir: blog
collections:
  tabs:
    output: true
  reprints:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

# SNS settings
weibo_username: 午后曳航hh
zhihu_username: 杭01
github_username: yanhh0
# twitter_username:

# Build settings
markdown: kramdown
