title: 午后曳航的博客
SEOTitle: 午后曳航的博客
email: yanhh0@163.com
theme: jekyll-theme-minimal

collections_dir: blog

collections:
  _edit:
    output: true

# SNS settings
weibo_username: 午后曳航hh
zhihu_username: 杭01
github_username: yanhh0
